version: 2.1

jobs:
  run-mabl-tests:
    docker:
      - image: mablhq/mabl-cli:latest
    steps:
      - run:
          name: Run Mabl Tests in CI
          command: |
            mabl tests run \
              --labels ci-cd \
              --application-id v8shDDOplBma19VTUWEkQA-a \
              --environment-id BbKahcHZaXCxvaDwV97Ugg-e 

workflows:
  version: 2
  run-tests:
    jobs:
      - run-mabl-tests
