version: 2.1

jobs:
  run-mabl-tests:
    docker:
      - image: mablhq/mabl-cli:latest
    steps:
      - run:
          name: Run Mabl Plan by Label
          command: |
            mabl tests run \
              --plan-labels ci-cd \
              --application-id v8shDDOplBma19VTUWEkQA-a \
              --environment-id BbKahcHZaXCxvaDwV97Ugg-e \
              --api-key $MABL_API_KEY

workflows:
  run-tests:
    jobs:
      - run-mabl-tests
