version: 2.1

jobs:
  run-mabl-tests:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout

      - run:
          name: Install Mabl CLI
          command: |
            curl -sSL https://downloads.mabl.com/cli/mabl-cli-linux -o mabl
            chmod +x mabl
            sudo mv mabl /usr/local/bin

      - run:
          name: Verify Mabl CLI version
          command: mabl --version

      - run:
          name: Run Mabl Plan by Label
          command: |
            mabl test run plan \
              --plan-labels ci-cd \
              --application-id v8shDDOplBma19VTUWEkQA-a \
              --environment-id BbKahcHZaXCxvaDwV97Ugg-e \
              --api-key $MABL_API_KEY

workflows:
  run-tests:
    jobs:
      - run-mabl-tests
