name: Run Mabl Tests
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Mabl Plan by Label
      uses: mablhq/github-run-tests-action@v1
      env:
        MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
      with:
     
         plan-labels: sauce-sit-ci-cd
         application-id: v8shDDOplBma19VTUWEkQA-a
         environment-id: BbKahcHZaXCxvaDwV97Ugg-e
