name: Run Mabl Tests

on:
  push:
    branches: [main]
  workflow_dispatch: # Manual run support

jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Mabl Plan
      uses: mablhq/github-run-tests-action@v1
      with:
        mabl-api-key: ${{ secrets.MABL_API_KEY }}
        plan-id: Vkg2mHV6UUVGcXn4pOCRjA-p  # Replace with actual plan-id
        environment-id: r03DV4ZJhPYccu9CetZ3eg-w  # Optional but recommended
